=== zrurf/PunklordeAssets/schema/MotionProfile.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "punklorde:schema:motion_profile",
    "title": "Motion Profile",
    "description": "用于运动模拟的运动数据文件",
    "type": "object",
    "properties": {
        "id": {
            "description": "运动文件的唯一ID",
            "type": "string",
            "pattern": "^[a-zA-Z0-9_:@-]+$"
        },
        "version": {
            "description": "运动文件的版本",
            "type": "integer"
        },
        "author": {
            "description": "作者",
            "type": "string"
        },
        "name": {
            "description": "显示的运动文件的名称",
            "type": "string"
        },
        "description": {
            "description": "运动文件的描述",
            "type": "string"
        },
        "repo": {
            "type": "array",
            "description": "查找轨迹文件的链接",
            "items": {
                "type": "string",
                "pattern": "^[a-zA-Z]+://[^\\s]+$"
            }
        },
        "data": {
            "description": "运动数据",
            "type": "object",
            "properties": {
                "paths": {
                    "description": "虚拟路径",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ext": {
                    "description": "",
                    "type": "object",
                    "additionalProperties": true
                }
            },
            "required": ["paths"]
        }
    },
    "required": ["id", "version", "name"]
}

=== zrurf/PunklordeAssets/data/MotionProfile/cqupt/fenghua/preset_1.motion.json
{
    "id": "cqupt:fenghua@p1",
    "name": "风华运动场:预设1",
    "version": 1,
    "description": "重庆邮电大学-风华运动场-预设1",
    "author": "Silver Wolf",
    "repo": ["https://cdn.jsdelivr.net/gh/zrurf/PunklordeAssets/data/"],
    "data": {
        "paths": ["cqupt:fenghua@vp1"],
        "ext": {
            "placeName": "风华运动场",
            "placeCode": "T1001"
        }
    }
}

=== zrurf/PunklordeAssets/data/MotionProfile/cqupt/fenghua/runway_1.motion.json
{
    "id": "cqupt:fenghua@rw1",
    "name": "风华运动场:预设跑道1道",
    "version": 1,
    "description": "重庆邮电大学-风华运动场-预设跑道1道",
    "author": "Silver Wolf",
    "repo": ["https://cdn.jsdelivr.net/gh/zrurf/PunklordeAssets/data/"],
    "data": {
        "paths": ["cqupt:fenghua@vpr1"],
        "ext": {
            "placeName": "风华运动场",
            "placeCode": "T1001"
        }
    }
}
