=== zrurf/PunklordeAssets/schema/VirtualPath.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "punklorde:schema:virtual_path",
    "title": "Virtual Path",
    "description": "虚拟路线数据文件",
    "type": "object",
    "properties": {
        "id": {
            "description": "路线的唯一ID",
            "type": "string",
            "pattern": "^[a-zA-Z0-9_:@-]+$"
        },
        "version": {
            "description": "路线的版本",
            "type": "integer"
        },
        "author": {
            "description": "作者",
            "type": "string"
        },
        "name": {
            "description": "显示的路线的名称",
            "type": "string"
        },
        "description": {
            "description": "路线的描述",
            "type": "string"
        },
        "points": {
            "description": "路线点",
            "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "lat": {
                            "type": "number"
                        },
                        "lng": {
                            "type": "number"
                        },
                        "alt": {
                            "type": "number"
                        }
                    },
                "required": ["lat", "lng"]
            }
        }
    },
    "required": ["id", "version", "name", "points"]
}

=== zrurf/PunklordeAssets/data/VirtualPath/cqupt/fenghua/vp_1.path.json
{
"id": "cqupt:fenghua@vp1",
"name": "风华运动场:虚拟路线1",
"description": "重庆邮电大学-风华运动场-虚拟路线1",
"version": 1,
"author": "Silver Wolf",
"points": [
{"lat": 29.532289496527778, "lng": 106.60705593532987},
{"lat": 29.53225830078125, "lng": 106.60705593532987},
{"lat": 29.532228461371528, "lng": 106.60705783420138},
{"lat": 29.53219943576389, "lng": 106.60706081814236},
{"lat": 29.532169325086805, "lng": 106.60706597222222},
{"lat": 29.53213650173611, "lng": 106.60708089192708},
{"lat": 29.532106391059028, "lng": 106.60710883246527},
{"lat": 29.532081434461805, "lng": 106.60713785807292},
{"lat": 29.532064344618057, "lng": 106.60717095269098},
{"lat": 29.53205132378472, "lng": 106.60720594618056},
{"lat": 29.53203830295139, "lng": 106.60723578559028},
{"lat": 29.53202826605903, "lng": 106.6072677951389},
{"lat": 29.53202338324653, "lng": 106.60730387369792},
{"lat": 29.5320263671875, "lng": 106.60734320746528},
{"lat": 29.532021484375, "lng": 106.60737928602431},
{"lat": 29.53201144748264, "lng": 106.60741807725694},
{"lat": 29.532003309461807, "lng": 106.60745307074653},
{"lat": 29.531996256510418, "lng": 106.60748806423611},
{"lat": 29.531993272569444, "lng": 106.60751925998264},
{"lat": 29.53198947482639, "lng": 106.60754909939236},
{"lat": 29.531988389756943, "lng": 106.60758110894098},
{"lat": 29.531988389756943, "lng": 106.60761420355902},
{"lat": 29.531988389756943, "lng": 106.60764838324653},
{"lat": 29.53199435763889, "lng": 106.60767849392361},
{"lat": 29.532003309461807, "lng": 106.60770833333333},
{"lat": 29.53200927734375, "lng": 106.60773844401042},
{"lat": 29.532019314236113, "lng": 106.60777452256944},
{"lat": 29.53203125, "lng": 106.60780653211806},
{"lat": 29.53204427083333, "lng": 106.60783447265625},
{"lat": 29.53206325954861, "lng": 106.607861328125},
{"lat": 29.532081434461805, "lng": 106.60788655598958},
{"lat": 29.53209933810764, "lng": 106.60790934244791},
{"lat": 29.53211941189236, "lng": 106.6079296875},
{"lat": 29.532141384548613, "lng": 106.60794976128473},
{"lat": 29.53216634114583, "lng": 106.60797173394097},
{"lat": 29.53219455295139, "lng": 106.60799370659723},
{"lat": 29.5322265625, "lng": 106.60801161024305},
{"lat": 29.532256673177084, "lng": 106.6080287000868},
{"lat": 29.532284613715277, "lng": 106.60803682204861},
{"lat": 29.53231363932292, "lng": 106.6080385876736},
{"lat": 29.532339680989583, "lng": 106.60803674175348},
{"lat": 29.532373589409723, "lng": 106.60803370486111},
{"lat": 29.53240966796875, "lng": 106.60802680121527},
{"lat": 29.53244466145833, "lng": 106.60801161024305},
{"lat": 29.532479654947917, "lng": 106.60800482855903},
{"lat": 29.532513563368056, "lng": 106.60800672743055},
{"lat": 29.532544759114582, "lng": 106.60801161024305},
{"lat": 29.53257351345486, "lng": 106.60801378038194},
{"lat": 29.532601725260417, "lng": 106.60801974826389},
{"lat": 29.53263156467014, "lng": 106.60802164713542},
{"lat": 29.53266167534722, "lng": 106.60802164713542},
{"lat": 29.532686631944443, "lng": 106.6080238172743},
{"lat": 29.532711588541666, "lng": 106.60802978515625},
{"lat": 29.532738715277777, "lng": 106.60803873697917},
{"lat": 29.532773708767362, "lng": 106.60803960373265},
{"lat": 29.532808702256943, "lng": 106.60804174175348},
{"lat": 29.53284884982639, "lng": 106.60804265668402},
{"lat": 29.532888997395833, "lng": 106.60804174175348},
{"lat": 29.53292697482639, "lng": 106.6080408107639},
{"lat": 29.532958984375, "lng": 106.60803870486111},
{"lat": 29.533017035590277, "lng": 106.60803168402778},
{"lat": 29.533044976128473, "lng": 106.60803168402778},
{"lat": 29.533074815538196, "lng": 106.6080287000868},
{"lat": 29.533103841145834, "lng": 106.60802463107639},
{"lat": 29.5331298828125, "lng": 106.60802680121527},
{"lat": 29.53315700954861, "lng": 106.6080287000868},
{"lat": 29.53318386501736, "lng": 106.60802463107639},
{"lat": 29.533208821614583, "lng": 106.6080238172743},
{"lat": 29.533234049479166, "lng": 106.6080238172743},
{"lat": 29.53325900607639, "lng": 106.6080238172743},
{"lat": 29.533286946614584, "lng": 106.6080238172743},
{"lat": 29.533314887152777, "lng": 106.60802164713542},
{"lat": 29.533339029947918, "lng": 106.60801459418403},
{"lat": 29.533364800347222, "lng": 106.60800862630208},
{"lat": 29.533388943142363, "lng": 106.6079966905382},
{"lat": 29.533414984809028, "lng": 106.60798366970486},
{"lat": 29.53344482421875, "lng": 106.60796359592014},
{"lat": 29.533471950954862, "lng": 106.60794460720486},
{"lat": 29.533495008680557, "lng": 106.60792182074653},
{"lat": 29.533518880208334, "lng": 106.60788981119792},
{"lat": 29.5335400390625, "lng": 106.60785481770833},
{"lat": 29.53355685763889, "lng": 106.60781955295138},
{"lat": 29.53356879340278, "lng": 106.6077845594618},
{"lat": 29.533578830295138, "lng": 106.60774929470486},
{"lat": 29.533584798177085, "lng": 106.6077183702257},
{"lat": 29.533591851128474, "lng": 106.60768636067708},
{"lat": 29.533594021267362, "lng": 106.60764946831597},
{"lat": 29.533599989149305, "lng": 106.60761149088542},
{"lat": 29.533607042100694, "lng": 106.60757134331597},
{"lat": 29.533610026041668, "lng": 106.60753851996527},
{"lat": 29.533612908854165, "lng": 106.60750813802083},
{"lat": 29.533613961805554, "lng": 106.60747911241319},
{"lat": 29.533614844618055, "lng": 106.60744927300347},
{"lat": 29.53361382855903, "lng": 106.6074191623264},
{"lat": 29.533611014756944, "lng": 106.60738606770833},
{"lat": 29.533609807725693, "lng": 106.60735622829861},
{"lat": 29.53360378689236, "lng": 106.60732421875},
{"lat": 29.533591753472223, "lng": 106.60729302300348},
{"lat": 29.533589952256943, "lng": 106.6072531467014},
{"lat": 29.533578830295138, "lng": 106.6072132703993},
{"lat": 29.533563910590278, "lng": 106.60718098958333},
{"lat": 29.533544921875, "lng": 106.60715277777778},
{"lat": 29.533516981336806, "lng": 106.60712782118055},
{"lat": 29.533491753472223, "lng": 106.60710394965278},
{"lat": 29.53346950954861, "lng": 106.60708875868056},
{"lat": 29.533448621961806, "lng": 106.6070738389757},
{"lat": 29.533423665364584, "lng": 106.60705376519097},
{"lat": 29.533394639756946, "lng": 106.60704399956597},
{"lat": 29.53337158203125, "lng": 106.607041015625},
{"lat": 29.533349609375, "lng": 106.60703884548612},
{"lat": 29.53332465277778, "lng": 106.60703884548612},
{"lat": 29.53329861111111, "lng": 106.60703776041667},
{"lat": 29.533269585503472, "lng": 106.60703586154514},
{"lat": 29.533238661024306, "lng": 106.60703884548612},
{"lat": 29.53320366753472, "lng": 106.6070458984375},
{"lat": 29.533169759114582, "lng": 106.60704779730902},
{"lat": 29.533138563368055, "lng": 106.6070458984375},
{"lat": 29.533111707899305, "lng": 106.60704779730902},
{"lat": 29.533083767361113, "lng": 106.60704888237848},
{"lat": 29.533058539496526, "lng": 106.60705783420138},
{"lat": 29.533029513888888, "lng": 106.60706081814236},
{"lat": 29.533001573350695, "lng": 106.60705783420138},
{"lat": 29.5329736328125, "lng": 106.60705891927083},
{"lat": 29.53294460720486, "lng": 106.60706298828126},
{"lat": 29.532916666666665, "lng": 106.60706597222222},
{"lat": 29.532889539930554, "lng": 106.60707085503472},
{"lat": 29.532861599392362, "lng": 106.6070738389757},
{"lat": 29.53282958984375, "lng": 106.60707275390625},
{"lat": 29.532801378038194, "lng": 106.60706298828126},
{"lat": 29.5327734375, "lng": 106.60706891927083},
{"lat": 29.53274929470486, "lng": 106.60706597222222},
{"lat": 29.532728407118057, "lng": 106.60706600911458},
{"lat": 29.532699381510415, "lng": 106.60706790798611},
{"lat": 29.53267333984375, "lng": 106.60706790798611},
{"lat": 29.532643500434027, "lng": 106.60707790798611},
{"lat": 29.532611490885415, "lng": 106.60707577473959},
{"lat": 29.532579481336807, "lng": 106.60707879557292},
{"lat": 29.532548285590277, "lng": 106.6070711485243},
{"lat": 29.53251925998264, "lng": 106.60707100260417},
{"lat": 29.532493489583334, "lng": 106.60707188541666},
{"lat": 29.532466362847224, "lng": 106.60707133836805},
{"lat": 29.532438422309028, "lng": 106.60707075217014},
{"lat": 29.532408311631944, "lng": 106.60706075217014},
{"lat": 29.532289496527778, "lng": 106.60705593532987}
]}

=== zrurf/PunklordeAssets/data/VirtualPath/cqupt/taichi/vp_r2.path.json
{
"id": "cqupt:taichi@vpr2",
"name": "太极运动场:跑道2",
"description": "重庆邮电大学-太极运动场-跑道2",
"version": 1,
"author": "Silver Wolf",
  "points": [
{"lat": 29.532675238715278, "lng": 106.60937608506944},
{"lat": 29.532650282118055, "lng": 106.60937608506944},
{"lat": 29.532629123263888, "lng": 106.60937798394097},
{"lat": 29.53260715060764, "lng": 106.60938015407986},
{"lat": 29.532584092881944, "lng": 106.60938015407986},
{"lat": 29.532560221354167, "lng": 106.60937798394097},
{"lat": 29.5325390625, "lng": 106.60937798394097},
{"lat": 29.532515190972223, "lng": 106.60937798394097},
{"lat": 29.532494303385416, "lng": 106.60938015407986},
{"lat": 29.53247016059028, "lng": 106.60938313802083},
{"lat": 29.532449273003472, "lng": 106.60938802083334},
{"lat": 29.53242485894097, "lng": 106.6093931749132},
{"lat": 29.532403971354167, "lng": 106.60940104166667},
{"lat": 29.532381998697918, "lng": 106.60941514756945},
{"lat": 29.532361924913193, "lng": 106.60942599826389},
{"lat": 29.53234185112847, "lng": 106.60944091796875},
{"lat": 29.532323947482638, "lng": 106.60945502387153},
{"lat": 29.53230685763889, "lng": 106.60947102864583},
{"lat": 29.5322900390625, "lng": 106.60949001736111},
{"lat": 29.532274848090278, "lng": 106.60950602213542},
{"lat": 29.532259928385418, "lng": 106.60952609592015},
{"lat": 29.53224880642361, "lng": 106.60954508463541},
{"lat": 29.53223388671875, "lng": 106.60956814236111},
{"lat": 29.53222195095486, "lng": 106.60959011501735},
{"lat": 29.5322119140625, "lng": 106.60961317274305},
{"lat": 29.532204047309026, "lng": 106.60963812934028},
{"lat": 29.532197265625, "lng": 106.6096630859375},
{"lat": 29.53219211154514, "lng": 106.60969129774305},
{"lat": 29.532189127604166, "lng": 106.60971842447917},
{"lat": 29.53218505859375, "lng": 106.60974636501736},
{"lat": 29.53218505859375, "lng": 106.609775390625},
{"lat": 29.53218722873264, "lng": 106.60980143229166},
{"lat": 29.532190212673612, "lng": 106.6098304578993},
{"lat": 29.532194281684028, "lng": 106.60985622829861},
{"lat": 29.53220024956597, "lng": 106.6098814561632},
{"lat": 29.53220730251736, "lng": 106.60990831163194},
{"lat": 29.532215169270835, "lng": 106.60993326822917},
{"lat": 29.532225206163194, "lng": 106.60995849609375},
{"lat": 29.532237141927084, "lng": 106.60998372395834},
{"lat": 29.532249077690974, "lng": 106.61000651041667},
{"lat": 29.532264268663194, "lng": 106.61003065321181},
{"lat": 29.5322802734375, "lng": 106.61005154079861},
{"lat": 29.532299262152776, "lng": 106.61007568359375},
{"lat": 29.53231906467014, "lng": 106.6100954861111},
{"lat": 29.532339138454862, "lng": 106.61011149088542},
{"lat": 29.532359212239584, "lng": 106.61012668185764},
{"lat": 29.53238226996528, "lng": 106.61014350043403},
{"lat": 29.5324072265625, "lng": 106.61015652126736},
{"lat": 29.532430555555557, "lng": 106.61017062717013},
{"lat": 29.532457411024307, "lng": 106.6101806640625},
{"lat": 29.53250949435764, "lng": 106.61019070095486},
{"lat": 29.53253255208333, "lng": 106.61019151475695},
{"lat": 29.532560492621528, "lng": 106.61019368489583},
{"lat": 29.532587348090278, "lng": 106.61019558376736},
{"lat": 29.53261257595486, "lng": 106.6101966688368},
{"lat": 29.53263943142361, "lng": 106.6101966688368},
{"lat": 29.532664388020834, "lng": 106.61019558376736},
{"lat": 29.5326904296875, "lng": 106.61019558376736},
{"lat": 29.53271538628472, "lng": 106.6101966688368},
{"lat": 29.532740342881944, "lng": 106.61019558376736},
{"lat": 29.532764485677085, "lng": 106.61019368489583},
{"lat": 29.532787543402776, "lng": 106.6101939561632},
{"lat": 29.53281032986111, "lng": 106.61019151475695},
{"lat": 29.532835557725694, "lng": 106.6101917860243},
{"lat": 29.532859429253474, "lng": 106.6101917860243},
{"lat": 29.53288547092014, "lng": 106.61019097222223},
{"lat": 29.53291232638889, "lng": 106.6101917860243},
{"lat": 29.532937554253472, "lng": 106.6101939561632},
{"lat": 29.532964409722222, "lng": 106.6101939561632},
{"lat": 29.532989366319445, "lng": 106.6101939561632},
{"lat": 29.533014322916667, "lng": 106.6101939561632},
{"lat": 29.533042534722224, "lng": 106.6101917860243},
{"lat": 29.533067491319443, "lng": 106.6101917860243},
{"lat": 29.533092447916665, "lng": 106.6101917860243},
{"lat": 29.53311767578125, "lng": 106.6101917860243},
{"lat": 29.533140733506944, "lng": 106.6101917860243},
{"lat": 29.533164605034724, "lng": 106.61019097222223},
{"lat": 29.533187662760415, "lng": 106.61019097222223},
{"lat": 29.533209635416668, "lng": 106.61018880208333},
{"lat": 29.53323269314236, "lng": 106.61018880208333},
{"lat": 29.533255750868054, "lng": 106.61019097222223},
{"lat": 29.533279622395835, "lng": 106.61019097222223},
{"lat": 29.533302680121526, "lng": 106.61019097222223},
{"lat": 29.53332763671875, "lng": 106.61018880208333},
{"lat": 29.533352864583332, "lng": 106.61018690321181},
{"lat": 29.533377821180554, "lng": 106.61018391927084},
{"lat": 29.53340060763889, "lng": 106.61017578125},
{"lat": 29.5334228515625, "lng": 106.61016682942709},
{"lat": 29.533445638020833, "lng": 106.61015597873264},
{"lat": 29.533467610677082, "lng": 106.61014350043403},
{"lat": 29.533489854600695, "lng": 106.61012858072917},
{"lat": 29.533509657118056, "lng": 106.61011149088542},
{"lat": 29.53352783203125, "lng": 106.61009358723959},
{"lat": 29.533545735677084, "lng": 106.61007568359375},
{"lat": 29.533562825520832, "lng": 106.6100537109375},
{"lat": 29.533577745225696, "lng": 106.61003363715278},
{"lat": 29.533590766059028, "lng": 106.61001166449653},
{"lat": 29.533602701822918, "lng": 106.60998860677083},
{"lat": 29.533612738715277, "lng": 106.60995659722222},
{"lat": 29.53363064236111, "lng": 106.60991672092014},
{"lat": 29.53364284939236, "lng": 106.60988552517361},
{"lat": 29.533647732204862, "lng": 106.6098513454861},
{"lat": 29.53365478515625, "lng": 106.60982638888889},
{"lat": 29.533655598958333, "lng": 106.60980034722222},
{"lat": 29.533655598958333, "lng": 106.60977837456598},
{"lat": 29.53365478515625, "lng": 106.60975341796875},
{"lat": 29.533650716145832, "lng": 106.60973036024305},
{"lat": 29.53364963107639, "lng": 106.6097083875868},
{"lat": 29.533647732204862, "lng": 106.60968532986111},
{"lat": 29.533640679253473, "lng": 106.609658203125},
{"lat": 29.53362250434028, "lng": 106.60959635416667},
{"lat": 29.53361056857639, "lng": 106.60956515842014},
{"lat": 29.533597547743057, "lng": 106.60953314887153},
{"lat": 29.533579372829863, "lng": 106.60950493706598},
{"lat": 29.5335595703125, "lng": 106.60948296440972},
{"lat": 29.53353732638889, "lng": 106.60946017795139},
{"lat": 29.533517523871527, "lng": 106.60944010416667},
{"lat": 29.533497450086806, "lng": 106.60941813151042},
{"lat": 29.533472493489583, "lng": 106.60940592447916},
{"lat": 29.533445366753472, "lng": 106.6093931749132},
{"lat": 29.53342041015625, "lng": 106.60938313802083},
{"lat": 29.533394368489585, "lng": 106.60937608506944},
{"lat": 29.533365342881943, "lng": 106.60937093098958},
{"lat": 29.53334038628472, "lng": 106.60936794704861},
{"lat": 29.5333154296875, "lng": 106.60936496310764},
{"lat": 29.533289388020833, "lng": 106.60936116536459},
{"lat": 29.533260362413195, "lng": 106.60936116536459},
{"lat": 29.53323459201389, "lng": 106.60936116536459},
{"lat": 29.533207465277776, "lng": 106.60936604817708},
{"lat": 29.533184407552085, "lng": 106.60937093098958},
{"lat": 29.533160264756944, "lng": 106.60937093098958},
{"lat": 29.533139105902777, "lng": 106.60937310112847},
{"lat": 29.533115234375, "lng": 106.60937310112847},
{"lat": 29.533092176649305, "lng": 106.60937798394097},
{"lat": 29.533070203993056, "lng": 106.60938015407986},
{"lat": 29.53304714626736, "lng": 106.60937798394097},
{"lat": 29.53302029079861, "lng": 106.60937798394097},
{"lat": 29.532995062934027, "lng": 106.60937798394097},
{"lat": 29.532969292534723, "lng": 106.60937798394097},
{"lat": 29.532942165798612, "lng": 106.60937798394097},
{"lat": 29.532915310329862, "lng": 106.60938015407986},
{"lat": 29.53289008246528, "lng": 106.60937608506944},
{"lat": 29.532862141927083, "lng": 106.60937608506944},
{"lat": 29.532835286458333, "lng": 106.60937608506944},
{"lat": 29.532807074652776, "lng": 106.609375},
{"lat": 29.532782118055554, "lng": 106.609375},
{"lat": 29.532755262586807, "lng": 106.609375},
{"lat": 29.532730305989585, "lng": 106.60937310112847},
{"lat": 29.53270724826389, "lng": 106.609375},
{"lat": 29.53268012152778, "lng": 106.609375},
{"lat": 29.532675238715278, "lng": 106.60937608506944}
  ]
}

=== zrurf/PunklordeAssets/data/VirtualPath/cqupt/fenghua/vp_r1.path.json
{
"id": "cqupt:fenghua@vpr1",
"name": "风华运动场:跑道1",
"description": "重庆邮电大学-风华运动场-跑道1",
"version": 1,
"author": "Silver Wolf",   
"points":[
{"lat":29.532296549479167,"lng":106.60797173394097},
{"lat":29.53231662326389,"lng":106.60796956380209},
{"lat":29.53233669704861,"lng":106.60796956380209},
{"lat":29.532359754774305,"lng":106.60797471788194},
{"lat":29.532381727430554,"lng":106.60798177083333},
{"lat":29.532406684027777,"lng":106.60798366970486},
{"lat":29.532431640625,"lng":106.60797878689236},
{"lat":29.532459581163195,"lng":106.60797173394097},
{"lat":29.532486707899306,"lng":106.6079736328125},
{"lat":29.5325146484375,"lng":106.60797878689236},
{"lat":29.53254665798611,"lng":106.60798177083333},
{"lat":29.532574598524306,"lng":106.60798366970486},
{"lat":29.53259955512153,"lng":106.60798177083333},
{"lat":29.53262451171875,"lng":106.60797661675348},
{"lat":29.53264865451389,"lng":106.60797471788194},
{"lat":29.53267361111111,"lng":106.60797471788194},
{"lat":29.532696668836806,"lng":106.6079736328125},
{"lat":29.53272162543403,"lng":106.60797173394097},
{"lat":29.532744683159724,"lng":106.60797173394097},
{"lat":29.532769639756946,"lng":106.60796956380209},
{"lat":29.532796766493057,"lng":106.60796956380209},
{"lat":29.532823621961807,"lng":106.60796956380209},
{"lat":29.532849663628472,"lng":106.60796875},
{"lat":29.532876519097222,"lng":106.60796875},
{"lat":29.532901746961805,"lng":106.60796875},
{"lat":29.53292697482639,"lng":106.60796875},
{"lat":29.53295193142361,"lng":106.60796657986111},
{"lat":29.532974989149306,"lng":106.60796468098958},
{"lat":29.532998860677083,"lng":106.60796169704861},
{"lat":29.53302001953125,"lng":106.60796169704861},
{"lat":29.5330419921875,"lng":106.60796169704861},
{"lat":29.53306694878472,"lng":106.60796468098958},
{"lat":29.533090006510417,"lng":106.60796875},
{"lat":29.533116861979167,"lng":106.60796875},
{"lat":29.533143988715278,"lng":106.60796956380209},
{"lat":29.533170030381946,"lng":106.60796956380209},
{"lat":29.533196885850696,"lng":106.60796875},
{"lat":29.533221842447915,"lng":106.60796468098958},
{"lat":29.53324896918403,"lng":106.60795871310764},
{"lat":29.533276909722222,"lng":106.60795166015625},
{"lat":29.533307020399306,"lng":106.60794460720486},
{"lat":29.533336859809026,"lng":106.60793972439237},
{"lat":29.53336181640625,"lng":106.60793158637152},
{"lat":29.5333837890625,"lng":106.60791965060764},
{"lat":29.533398980034722,"lng":106.60789957682292},
{"lat":29.533413899739582,"lng":106.6078746202257},
{"lat":29.533428819444445,"lng":106.60784857855903},
{"lat":29.53343994140625,"lng":106.60782443576389},
{"lat":29.53345404730903,"lng":106.60779839409722},
{"lat":29.533464898003473,"lng":106.60776936848958},
{"lat":29.533474934895832,"lng":106.6077414279514},
{"lat":29.533484971788194,"lng":106.60771131727431},
{"lat":29.533492024739584,"lng":106.6076833767361},
{"lat":29.533498806423612,"lng":106.60765652126736},
{"lat":29.533501790364582,"lng":106.6076283094618},
{"lat":29.533501790364582,"lng":106.60759847005208},
{"lat":29.533501790364582,"lng":106.60756646050348},
{"lat":29.533498806423612,"lng":106.60753445095486},
{"lat":29.53349392361111,"lng":106.60750325520833},
{"lat":29.533489854600695,"lng":106.60747314453126},
{"lat":29.53348388671875,"lng":106.6074462890625},
{"lat":29.53347683376736,"lng":106.6074191623264},
{"lat":29.53346896701389,"lng":106.60739312065972},
{"lat":29.53345703125,"lng":106.60736626519098},
{"lat":29.533444010416666,"lng":106.60734103732639},
{"lat":29.533429904513888,"lng":106.60731906467014},
{"lat":29.533413899739582,"lng":106.60729817708334},
{"lat":29.533396809895834,"lng":106.6072740342882},
{"lat":29.53337863498264,"lng":106.60725423177084},
{"lat":29.53335666232639,"lng":106.60723415798611},
{"lat":29.533331705729168,"lng":106.60721896701389},
{"lat":29.533304578993057,"lng":106.60720377604167},
{"lat":29.533279622395835,"lng":106.6071888563368},
{"lat":29.53325656467014,"lng":106.60717800564237},
{"lat":29.53323459201389,"lng":106.60716878255208},
{"lat":29.533213704427084,"lng":106.60716281467013},
{"lat":29.533189561631943,"lng":106.60716281467013},
{"lat":29.533163519965278,"lng":106.60715901692708},
{"lat":29.533133680555554,"lng":106.60715576171874},
{"lat":29.533104654947916,"lng":106.60715277777778},
{"lat":29.53307861328125,"lng":106.60714599609375},
{"lat":29.53304958767361,"lng":106.60714789496528},
{"lat":29.533023546006945,"lng":106.60715087890625},
{"lat":29.532996690538194,"lng":106.60715386284723},
{"lat":29.532971733940972,"lng":106.60715386284723},
{"lat":29.532948676215277,"lng":106.60715576171874},
{"lat":29.532926703559028,"lng":106.60715901692708},
{"lat":29.532899576822917,"lng":106.60716091579862},
{"lat":29.53287163628472,"lng":106.60716091579862},
{"lat":29.5328466796875,"lng":106.60716281467013},
{"lat":29.532819552951388,"lng":106.6071657986111},
{"lat":29.532796766493057,"lng":106.60716878255208},
{"lat":29.532773708767362,"lng":106.60717095269098},
{"lat":29.53274848090278,"lng":106.60716878255208},
{"lat":29.532723253038196,"lng":106.60716389973959},
{"lat":29.532696397569445,"lng":106.60716281467013},
{"lat":29.53266845703125,"lng":106.60716281467013},
{"lat":29.53264133029514,"lng":106.60716389973959},
{"lat":29.532616373697916,"lng":106.6071657986111},
{"lat":29.532591417100694,"lng":106.6071657986111},
{"lat":29.532568359375,"lng":106.60716796875},
{"lat":29.53253933376736,"lng":106.60716389973959},
{"lat":29.532513292100695,"lng":106.60716281467013},
{"lat":29.532486436631945,"lng":106.60716091579862},
{"lat":29.532461480034723,"lng":106.60715901692708},
{"lat":29.532434353298612,"lng":106.60715793185764},
{"lat":29.53240939670139,"lng":106.60716281467013},
{"lat":29.532386338975694,"lng":106.60717393663194},
{"lat":29.532361382378472,"lng":106.6071839735243},
{"lat":29.53233344184028,"lng":106.60719292534722},
{"lat":29.532306315104165,"lng":106.6071959092882},
{"lat":29.532278374565973,"lng":106.60720377604167},
{"lat":29.53225341796875,"lng":106.60720893012153},
{"lat":29.532229275173613,"lng":106.60721896701389},
{"lat":29.532208387586806,"lng":106.60723578559028},
{"lat":29.532186414930557,"lng":106.60726101345486},
{"lat":29.532169325086805,"lng":106.60728895399305},
{"lat":29.53215847439236,"lng":106.60731418185765},
{"lat":29.53214626736111,"lng":106.60733913845486},
{"lat":29.53213134765625,"lng":106.60736409505208},
{"lat":29.53211642795139,"lng":106.60739312065972},
{"lat":29.532103407118054,"lng":106.60741617838542},
{"lat":29.532093370225695,"lng":106.60743815104166},
{"lat":29.53208441840278,"lng":106.60745903862848},
{"lat":29.53207845052083,"lng":106.60747911241319},
{"lat":29.532073296440974,"lng":106.6075062391493},
{"lat":29.532071397569446,"lng":106.60753119574653},
{"lat":29.532071397569446,"lng":106.60755913628472},
{"lat":29.532071397569446,"lng":106.60759114583334},
{"lat":29.532071397569446,"lng":106.60761908637153},
{"lat":29.532071397569446,"lng":106.60764431423611},
{"lat":29.532074381510416,"lng":106.60767333984376},
{"lat":29.532083333333333,"lng":106.6077064344618},
{"lat":29.532094455295137,"lng":106.60773654513889},
{"lat":29.53211127387153,"lng":106.60776638454861},
{"lat":29.532128363715277,"lng":106.6077964952257},
{"lat":29.53213948567708,"lng":106.60781955295138},
{"lat":29.532154405381945,"lng":106.60783854166667},
{"lat":29.532169325086805,"lng":106.6078564453125},
{"lat":29.532186414930557,"lng":106.60787434895833},
{"lat":29.532203504774305,"lng":106.60789143880208},
{"lat":29.53222140842014,"lng":106.60790635850694},
{"lat":29.532239583333332,"lng":106.60791965060764},
{"lat":29.53225857204861,"lng":106.60793158637152},
{"lat":29.53227973090278,"lng":106.60794460720486},
{"lat":29.532296549479167,"lng":106.60797173394097}
]
}
